name: habbit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  google_fonts: ^0.4.1
  flutter_colorpicker: ^0.3.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/activities/
    - assets/
